version: '3.8'
name: guestservice
volumes:
  data:
      driver: local

services:
  postgres:
      container_name: postgres-guestservice
      image: postgres
      volumes:
        - data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
      ports:
      - 5432:5432
  postgres-pgadmin4:
      container_name: pgadmin4-guestservice
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: k12345689@students.jku.at
        PGADMIN_DEFAULT_PASSWORD: password
      ports:
        - 5050:80
      depends_on:
        - postgres
  keycloak:
      container_name: keycloak-guestservice
      image: quay.io/keycloak/keycloak:legacy
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
      ports:
        - 8081:8080
      depends_on:
        - postgres

